### ISSUE TITLE
Config Screen is to long for the normal PC Screen

### ISSUE THREAD

**Issue by Titoo8899** [TheHamester/HitIndicator#1]
Hi,
the Config of your mod is to long and can not complete see on a normal PC Screen. I hope you can with this Picture this Problem fix.

<img width="960" alt="Screenshot 2023-04-11 185405" src="https://user-images.githubusercontent.com/42325138/231234885-4736f11d-d03f-4848-991d-a418e77edbf2.png">

**Comment by TheHamester** [comment]
There's acouple ways to fix this:

You can change the Gui scale in the minecraft video settings to a scale that is smaller.
You can also hover over the text in the config for a description to appear, telling you what it does.
Lastly, you can go into the config folder in your instance, and find "HitIndication.cfg".

Unfortunately, other than that, I'm not sure if we can do anything, cause the config menu is something added by the Forge mod loader itself and has nothing to do with our mod.
