### ISSUE TITLE
[1.16.5] is this a bug?

### ISSUE THREAD

**Issue by Daejangnamu** [TheHamester/HitIndicator#14]
[[https://youtu.be/DXuCN6_jcWU]](https://youtu.be/DXuCN6_jcWU)

If you attack from a distance, the indicator is invisible
I use gun mods 
I want the indicator to work even if I attack the player from a distance

**Comment by TheHamester** [comment]
It's a feature when entity is farther away the indicator becomes gradually smaller after 10 blocks up until 20 blocks when it becomes invisible.

**Comment by TheHamester** [comment]
i can probably make it a config option next update, but for now you can use an earlier version 1.2.2 without that feature

**Comment by TheHamester** [comment]
released 1.2.4

* Added config option to enable distance scaling
* Added config option for distance scaling cutoff
