### ISSUE TITLE
The mod does not work on the server

### ISSUE THREAD

**Issue by Ratm1kkk** [TheHamester/HitIndicator#17]
I installed the mod on both my client and server. But the mod only works in single player mode

**Comment by TheHamester** [comment]
what version of minecraft and does that happen on latest build?

**Comment by TheHamester** [comment]
just verified on latest version of minecraft 1.20.4 and version of mod 1.3.1 it does show indicators on the server. could you provide more detail about your setup?

**Comment by TheHamester** [comment]
also didnt accept discord friend request cause didnt have any friends in common, i thought it was spam, sorry about that

**Comment by Ratm1kkk** [comment]
1.16.5 mohist server, i can see blue indicators when block, but the red indicators are not working(((

**Comment by TheHamester** [comment]
https://github.com/MohistMC/Mohist/issues/2674
