### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by SettingDust** [TheHamester/HitIndicator#2]
https://github.com/TheHamester/HitIndicator/blob/c72a313aaadaca4937ca8ac5dbcc12e0b2bd4792/src/main/java/com/rosymaple/hitindication/event/HitEvents.java#L36

Please using logger next time. Take hours from some people for find the reason of spam

**Comment by TheHamester** [comment]
will be taken care of in the next update, sorry of the inconvinience

**Comment by SettingDust** [comment]
> will be taken care of in the next update, sorry of the inconvinience

It's fine

**Comment by TheHamester** [comment]
Done!
