### ISSUE TITLE
Terrafirmacraft Incompatibility?

### ISSUE THREAD

**Issue by SheReyy** [TheHamester/HitIndicator#20]
MC version: 1.20.1
Forge: 47.3.0
Hit Indication: hitindication-1.20.1-1.4.jar
TFC: TerraFirmaCraft-Forge-1.20.1-3.2.5.jar

The mod won't work when it's installed along side with [Terrafirmacraft](https://www.curseforge.com/minecraft/mc-mods/terrafirmacraft). No indicators would appear whenever the player is hit, or when they block an attack. [Here](https://gist.github.com/SheReyy/55b1a0caa03d0e37e33f6506447b8e21)'s my log file

**Comment by TheHamester** [comment]
terrafirmacraft apperently mixins into health and xp rendering. changed the overlay layer that i draw indicators to "hotbar", and now theres no conflict

**Comment by TheHamester** [comment]
will upload 1.5 soon

**Comment by TheHamester** [comment]
fixed in 1.5 https://github.com/TheHamester/HitIndicator/releases/tag/1.20.1-1.5

**Comment by TheHamester** [comment]
see recent comments to: https://github.com/TheHamester/HitIndicator/issues/19
this fix will make the later 1.5 release, but proximity indicators might not, the jar to unlisted version you can also find there

**Comment by SheReyy** [comment]
Can you hold the 1.5 release for a bit? I've got another mod that's incompatible with Hit Indication. I added the mod to my main mod pack instance and it doesn't work there. I'm trying to figure out which mod might be at fault. I'm also running tests with some other mods that have a screen overlay. I'll post proper issues for each of them if any problems appear

**Comment by SheReyy** [comment]
Ok, I narrowed it down to 4 possible mods
