### ISSUE TITLE
[Question] What happened to the CurseForge version?

### ISSUE THREAD

**Issue by Looodon** [TheHamester/HitIndicator#24]
Hey,
I downloaded "Hit Indication" through CurseForge but now it's removed. Was wondering if that was actually uploaded by you or a malicious copy! Will it be back up or is modrinth the place to access it from now on?
![Screen Shot (2024-11-21 07_42_59)](https://github.com/user-attachments/assets/63c90d5c-f22d-4fd2-9277-7249814dd676)

**Comment by TheHamester** [comment]
Hit indication has been uploaded and removed from CurseForge by me. And now will only be available on Modrinth.
