### ISSUE TITLE
Made Damage Indicators can be disabled

### ISSUE THREAD

**Issue by HaHaWTH** [TheHamester/HitIndicator#5]
When I installed the mod, I found that the damage indicator(i mean receiving damage here, not doing damage) cannot be disabled in 1.12.2, hope you can make this configurable❤

**Comment by TheHamester** [comment]
Sorry to inform that this is not a planned feature. Hit markers were added as an additional secondary feature, hence they are disablable. However, hit indication is the core idea of the mod.

**Comment by TheHamester** [comment]
will be configurable in the next patch, and added with chinese localization.

**Comment by TheHamester** [comment]
https://github.com/TheHamester/HitIndicator/commit/33998aef9b5839e59cc672ba3cd9ae3482c4a3e1
https://github.com/TheHamester/HitIndicator/commit/b608f8f24cbae89989ffd475ddb81aaf04804239
https://github.com/TheHamester/HitIndicator/commit/56a2e52aaa7388f1efbc1cdac583639c0dd3ef16
